export const CURRENCE_CONVERT = 23350;
export const PAYMENT_DEPOSIT = "PAYMENT_DEPOSIT";
export const PAYMENT_STATUS = {
  WAITING_CREATE_BILL: "WAITING_CREATE_BILL",
  NOT_YET: "NOT_YET",
  PAID: "PAID",
};
