export interface SearchParams {
    city: string,
    district: string[],
    ward: string,
    minPrice: number,
    maxPrice: number,
    utilities_bed: boolean,
    utilities_wm: boolean,
    utilities_time: boolean,
    utilities_ac: boolean,
    utilities_refrigerator: boolean,
    utilities_wifi: boolean,
    utilities_parking: boolean,
    utilities_toilet: boolean,
    utilities_kitchen: boolean,
    utilities_television: boolean,
    dormitory: boolean,
    roomForRent: boolean,
    apartment: boolean,
    wholeHouse: boolean,
    sharedRoom: boolean,
    sortBy: string,
    page: number

    // constructor = {
    //     city: "",
    //     district: "",
    //     ward: "",
    //     streetName: "",
    //     search: "",
    //     minPrice: 0,
    //     maxPrice: 20000,
    //     utilities_bed: false,
    //     utilities_wm: false,
    //     utilities_time: false,
    //     utilities_ac: false,
    //     utilities_refrigerator: false,
    //     utilities_wifi: false,
    //     utilities_parking: false,
    //     utilities_toilet: false,
    //     utilities_kitchen: false,
    //     dormitory: false,
    //     roomForRent: false,
    //     apartment: false,
    //     wholeHouse: false,
    //     sharedRoom: false,
    //     sortBy: "latest",
    //     page: 1
    // }
}