export const NOTIFICATION_TYPE = {
  DEPOSIT: "DEPOSIT",
  BECOME_INNKEEPER: "BECOME INNKEEPER",
  ACCEPT_OR_REJECT: "ACCEPT OR REJECT",
  CREATE_CONTRACT: "CREATE CONTRACT",
  SIGN_CONTRACT: "SIGN CONTRACT",
};
